AWSTemplateFormatVersion: '2010-09-09'
Description: VPC
Parameters:
  VpcCIDRStart:
    Description: The start of the /16 cidr block for the vpc
    Type: String
    MinLength: '3'
    MaxLength: '7'
    Default: '10.21'
    AllowedPattern: (\d{1,3})\.(\d{1,3})
    ConstraintDescription: must be of the form x.x
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: !Sub
        - ${CIDRstart}.0.0/16
        - CIDRstart: !Ref 'VpcCIDRStart'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackName'
Outputs:
  VPCId:
    Description: VPCId of the newly created VPC
    Value: !Ref 'VPC'
    Export:
      Name: !Sub '${AWS::StackName}-VPCID'
  VpcCIDRStart:
    Description: The start of the /16 cidr block for the vpc
    Value: !Ref 'VpcCIDRStart'
    Export:
      Name: !Sub '${AWS::StackName}-VpcCIDRStart'
